name: Paul Bratcher Photography
favicon: null
layout_spectrum: 0.2175
typography_spectrum: 0.22676
title: Paul Bratcher Photography - Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#77b3df'
    - '#1d3b55'
    - '#548bb9'
    - '#d0dee1'
  brandStrength: 0.1875
  lightness: 0.6762109091505408
  saturation: 0.9861635237466544
  rhythmicContrast: 0.19679260882548988
purpose: []
